require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GNotesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # GNote. As you add validations to GNote, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GNotesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all g_notes as @g_notes" do
      g_note = GNote.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:g_notes)).to eq([g_note])
    end
  end

  describe "GET show" do
    it "assigns the requested g_note as @g_note" do
      g_note = GNote.create! valid_attributes
      get :show, {:id => g_note.to_param}, valid_session
      expect(assigns(:g_note)).to eq(g_note)
    end
  end

  describe "GET new" do
    it "assigns a new g_note as @g_note" do
      get :new, {}, valid_session
      expect(assigns(:g_note)).to be_a_new(GNote)
    end
  end

  describe "GET edit" do
    it "assigns the requested g_note as @g_note" do
      g_note = GNote.create! valid_attributes
      get :edit, {:id => g_note.to_param}, valid_session
      expect(assigns(:g_note)).to eq(g_note)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GNote" do
        expect {
          post :create, {:g_note => valid_attributes}, valid_session
        }.to change(GNote, :count).by(1)
      end

      it "assigns a newly created g_note as @g_note" do
        post :create, {:g_note => valid_attributes}, valid_session
        expect(assigns(:g_note)).to be_a(GNote)
        expect(assigns(:g_note)).to be_persisted
      end

      it "redirects to the created g_note" do
        post :create, {:g_note => valid_attributes}, valid_session
        expect(response).to redirect_to(GNote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved g_note as @g_note" do
        post :create, {:g_note => invalid_attributes}, valid_session
        expect(assigns(:g_note)).to be_a_new(GNote)
      end

      it "re-renders the 'new' template" do
        post :create, {:g_note => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested g_note" do
        g_note = GNote.create! valid_attributes
        put :update, {:id => g_note.to_param, :g_note => new_attributes}, valid_session
        g_note.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested g_note as @g_note" do
        g_note = GNote.create! valid_attributes
        put :update, {:id => g_note.to_param, :g_note => valid_attributes}, valid_session
        expect(assigns(:g_note)).to eq(g_note)
      end

      it "redirects to the g_note" do
        g_note = GNote.create! valid_attributes
        put :update, {:id => g_note.to_param, :g_note => valid_attributes}, valid_session
        expect(response).to redirect_to(g_note)
      end
    end

    describe "with invalid params" do
      it "assigns the g_note as @g_note" do
        g_note = GNote.create! valid_attributes
        put :update, {:id => g_note.to_param, :g_note => invalid_attributes}, valid_session
        expect(assigns(:g_note)).to eq(g_note)
      end

      it "re-renders the 'edit' template" do
        g_note = GNote.create! valid_attributes
        put :update, {:id => g_note.to_param, :g_note => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested g_note" do
      g_note = GNote.create! valid_attributes
      expect {
        delete :destroy, {:id => g_note.to_param}, valid_session
      }.to change(GNote, :count).by(-1)
    end

    it "redirects to the g_notes list" do
      g_note = GNote.create! valid_attributes
      delete :destroy, {:id => g_note.to_param}, valid_session
      expect(response).to redirect_to(g_notes_url)
    end
  end

end
